plugins {
    id 'application'
}

application {
    mainClass = 'com.genymobile.gnirehtet.Main'
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    testImplementation 'junit:junit:4.13.2'
}

jar {
    manifest {
        attributes(
                'Main-Class': application.mainClass
        )
    }
    archiveBaseName = 'gnirehtet'
}

tasks.register('assembleDebug') { dependsOn 'jar' }
tasks.register('assembleRelease') { dependsOn 'build', 'jar' }

apply from: "$project.rootDir/config/java-checkstyle.gradle"

test {
    // to log using System.out.println(…) in tests
    testLogging.showStandardStreams = true
}
