apply plugin: 'checkstyle'

checkstyle {
    toolVersion = '6.19'
}

tasks.register('checkstyle', Checkstyle) {
    description = "Check Java style with Checkstyle"
    configFile = rootProject.file("config/checkstyle/checkstyle.xml")
    source = files('src/main/java', 'src/test/java').filter { it.exists() }
    classpath = files()
    ignoreFailures = true
}

tasks.named('check') { dependsOn 'checkstyle' }
